### ISSUE TITLE
width, height = os.get_terminal_size(); OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by MichaelDRichards** [sharkba1t/you-woke-up-in-your-room#1]
$ py you-woke-up-in-your-room.py
Traceback (most recent call last):
  File "C:\Users\mdric\OneDrive\Projects\you-woke-up-in-your-room\you-woke-up-in-your-room.py", line 7, in <module>
    width, height = os.get_terminal_size()
OSError: [WinError 6] The handle is invalid

-----

$ py --version
Python 3.10.1

-----

$ uname -a
MINGW64_NT-10.0-19042 SurfacePro 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys

**Comment by sharkba1t** [comment]
I removed that line of code in the new update. It should be fixed now.
